version: "3.9"

services:
  web:
    build: .
    working_dir: /code/app
    env_file:
      - .env
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      PYTHONPATH: /code
      DEBUG: 1
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_KEY: ${QDRANT_KEY}
    volumes:
      - ./app:/code/app
    restart: on-failure
    command:
      [
        "python",
        "-m",
        "debugpy",
        "--wait-for-client",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--reload",
      ]
