services:
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_KEY: ${QDRANT_KEY}
