version: "3.9"

services:
  web:
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      PYTHONPATH: /code
      DEBUG: 1
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_KEY: ${QDRANT_KEY}
    volumes:
      - ./app:/code/app
    restart: on-failure
